### PR TITLE
new version of celements-RTE

### PR DESCRIPTION
**Pull request by dkhasham**
https://synjira.atlassian.net/browse/CELDEV-679

### CODE REVIEW

**Comment by msladek** [comment]
please update parent `base-pom`

**Review by msladek — CHANGES_REQUESTED** [review]
please update parent `base-pom`

**Comment by fpichler** [comment]
Please do not change the version in cel-rte master. Start a new branch or even project for version 4. Ensure that we can use both versions in paralell concurrently in the same celements-release.

**Comment by dkhasham** [comment]
WorkingTree has now 2 projects:
- TinyMCEv3
- TinyMCEv4

**Review by fpichler — DISMISSED** [review]

**Review by msladek — DISMISSED** [review]

**Review by msladek — APPROVED** [review]

**Pull request merged**
